name: rayenv2
channels:
  - defaults
dependencies:
  - ca-certificates=2025.2.25
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.9.21
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.2.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiohttp-cors==0.8.1
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.9.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - cachetools==5.5.2
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.1.8
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorful==0.5.6
      - contourpy==1.3.0
      - cycler==0.12.1
      - distlib==0.3.9
      - dm-tree==0.1.8
      - exceptiongroup==1.2.2
      - farama-notifications==0.0.4
      - fastapi==0.115.12
      - filelock==3.18.0
      - flatbuffers==25.2.10
      - fonttools==4.58.0
      - frozenlist==1.6.0
      - fsspec==2025.3.2
      - google-api-core==2.24.2
      - google-auth==2.40.1
      - googleapis-common-protos==1.70.0
      - grpcio==1.71.0
      - gymnasium==1.1.1
      - h11==0.16.0
      - h5py==3.13.0
      - httptools==0.6.4
      - humanfriendly==10.0
      - idna==3.10
      - importlib-metadata==4.13.0
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.7
      - llvmlite==0.43.0
      - lz4==4.4.4
      - markdown==3.8
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.4.3
      - networkx==3.2.1
      - numba==0.60.0
      - numpy==2.0.2
      - onnx==1.17.0
      - onnxruntime==1.19.2
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - packaging==25.0
      - pandas==2.2.3
      - pillow==11.2.1
      - platformdirs==4.3.8
      - prometheus-client==0.21.1
      - propcache==0.3.1
      - proto-plus==1.26.1
      - protobuf==6.30.2
      - py-spy==0.4.0
      - pyarrow==20.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pyparsing==3.2.3
      - pyqt6==6.9.1
      - pyqt6-qt6==6.9.1
      - pyqt6-sip==13.10.2
      - pyqtgraph==0.13.7
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - ray==2.46.0
      - referencing==0.36.2
      - requests==2.32.3
      - rpds-py==0.24.0
      - rsa==4.9.1
      - scipy==1.13.1
      - six==1.17.0
      - smart-open==7.1.0
      - sniffio==1.3.1
      - starlette==0.46.2
      - sympy==1.14.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - torch==2.7.0
      - torchaudio==2.7.0
      - torchvision==0.22.0
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - urllib3==2.4.0
      - uvicorn==0.34.2
      - uvloop==0.21.0
      - virtualenv==20.31.1
      - watchfiles==1.0.5
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - yarl==1.20.0
      - zipp==3.21.0
